version: "3.4"

services:
  serverService:
    image: yulikdaniel/mafia_server
    environment:
      SERVER_PORT: 5075
    ports:
      - 5075:5075

  clientService1:
    image: yulikdaniel/mafia_client  
    environment:
      SERVER_ADDRESS: serverService:5075
      CLIENT_ADDRESS: clientService1:5076
      CLIENT_PORT: 5076
    ports:
      - 5076:5076
    depends_on:
      - serverService

  clientService2:
    image: yulikdaniel/mafia_client
    environment:
      SERVER_ADDRESS: serverService:5075
      CLIENT_ADDRESS: clientService2:5077
      CLIENT_PORT: 5077
    ports:
      - 5077:5077
    depends_on:
      - serverService

  clientService3:
    image: yulikdaniel/mafia_client
    environment:
      SERVER_ADDRESS: serverService:5075
      CLIENT_ADDRESS: clientService3:5078
      CLIENT_PORT: 5078
    ports:
      - 5078:5078
    depends_on:
      - serverService

  clientService4:
    image: yulikdaniel/mafia_client
    environment:
      SERVER_ADDRESS: serverService:5075
      CLIENT_ADDRESS: clientService4:5079
      CLIENT_PORT: 5079
    ports:
      - 5079:5079
    depends_on:
      - serverService

  clientService5:
    image: yulikdaniel/mafia_client
    environment:
      SERVER_ADDRESS: serverService:5075
      CLIENT_ADDRESS: clientService5:5080
      CLIENT_PORT: 5080
    ports:
      - 5080:5080
    depends_on:
      - serverService

  clientService6:
    image: yulikdaniel/mafia_client
    environment:
      SERVER_ADDRESS: serverService:5075
      CLIENT_ADDRESS: clientService6:5081
      CLIENT_PORT: 5081
    ports:
      - 5081:5081
    depends_on:
      - serverService

  clientService7:
    image: yulikdaniel/mafia_client
    environment:
      SERVER_ADDRESS: serverService:5075
      CLIENT_ADDRESS: clientService7:5082
      CLIENT_PORT: 5082
    ports:
      - 5082:5082
    depends_on:
      - serverService

  clientService8:
    image: yulikdaniel/mafia_client
    environment:
      SERVER_ADDRESS: serverService:5075
      CLIENT_ADDRESS: clientService8:5083
      CLIENT_PORT: 5083
    ports:
      - 5083:5083
    depends_on:
      - serverService

  clientService9:
    image: yulikdaniel/mafia_client
    environment:
      SERVER_ADDRESS: serverService:5075
      CLIENT_ADDRESS: clientService9:5084
      CLIENT_PORT: 5084
    ports:
      - 5084:5084
    depends_on:
      - serverService