version: "3.4"

services:
  serverService:
    image: yulikdaniel/mafia_server
    environment:
      SERVER_PORT: 5075
    ports:
      - 5075:5075

  clientService1:
    image: yulikdaniel/mafia_client  
    environment:
      SERVER_ADDRESS: serverService:5075
      CLIENT_ADDRESS: clientService1:5076
      CLIENT_PORT: 5076
    ports:
      - 5076:5076
    depends_on:
      - serverService

  clientService2:
    image: yulikdaniel/mafia_client
    environment:
      SERVER_ADDRESS: serverService:5075
      CLIENT_ADDRESS: clientService2:5077
      CLIENT_PORT: 5077
    ports:
      - 5077:5077
    depends_on:
      - serverService

  clientService3:
    image: yulikdaniel/mafia_client
    environment:
      SERVER_ADDRESS: serverService:5075
      CLIENT_ADDRESS: clientService3:5078
      CLIENT_PORT: 5078
    ports:
      - 5078:5078
    depends_on:
      - serverService

  clientService4:
    image: yulikdaniel/mafia_client
    environment:
      SERVER_ADDRESS: serverService:5075
      CLIENT_ADDRESS: clientService4:5079
      CLIENT_PORT: 5079
    ports:
      - 5079:5079
    depends_on:
      - serverService

  clientService5:
    image: yulikdaniel/mafia_client
    environment:
      SERVER_ADDRESS: serverService:5075
      CLIENT_ADDRESS: clientService5:5080
      CLIENT_PORT: 5080
    ports:
      - 5080:5080
    depends_on:
      - serverService